# Generated by Django 3.2.5 on 2021-09-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_mailmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='email',
            new_name='email1',
        ),
    ]
