# Generated by Django 3.2.5 on 2021-09-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_email_newsletteruser_email1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='email1',
            new_name='email',
        ),
    ]
