# Generated by Django 3.2.5 on 2021-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_rename_email1_newsletteruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
