# Generated by Django 3.2.5 on 2021-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_newsletteruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='conf_num',
            field=models.CharField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletteruser',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
