# Generated by Django 3.2.5 on 2021-10-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_newsletteruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
