# Generated by Django 3.2.5 on 2021-09-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210907_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_description',
            name='faq_description_1',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='site_description',
            name='faq_description_2',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site_description',
            name='privacy_description_1',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='site_description',
            name='privacy_description_2',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site_description',
            name='terms_description_1',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='site_description',
            name='terms_description_2',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=500, null=True),
        ),
    ]
