# Generated by Django 3.2.5 on 2021-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210913_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_description',
            name='jumbotron',
            field=models.TextField(blank=True, default='Wpisz opis w panelu admin', max_length=500, null=True),
        ),
    ]
