# Generated by Django 3.2.5 on 2021-09-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Podaj imię i nazwisko lub unikalną nazwę klienta', max_length=50),
        ),
    ]
