# Generated by Django 3.2.5 on 2021-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=80, verbose_name='Adres klienta'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Podaj imię i nazwisko lub unikalną nazwę klienta', max_length=50, unique=True, verbose_name='Nazwa klienta'),
        ),
    ]
