# Generated by Django 3.2.5 on 2021-10-20 11:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210917_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
