# Generated by Django 3.2.5 on 2021-10-20 15:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20211020_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
