# Generated by Django 3.2.5 on 2021-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210809_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.IntegerField(default=1, verbose_name='Dostępność produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Opis produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_picture.png', help_text='! UWAGA ! - Zdjęcie musi mieć dokładnie 450x450 pixeli - ! UWAGA !', upload_to='products', verbose_name='Zdjęcie produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text=' PLN', verbose_name='Cena produktu'),
        ),
    ]
