# Generated by Django 3.2.5 on 2021-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210917_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_picture.png', help_text='ZDJĘCIE MIUSI MIEĆ 450x450 px!', upload_to='products', verbose_name='Zdjęcie produktu'),
        ),
    ]
